# Generated by Django 3.0.4 on 2020-04-21 00:18

from django.db import migrations, models
import django.db.models.deletion
import peer_assessment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('instructor_list_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(default='16943834', max_length=100)),
                ('eagle_id', models.CharField(max_length=8, unique=True, validators=[peer_assessment.models.User.validate_digit_length], verbose_name='id')),
                ('type', models.CharField(choices=[('S', 'Student'), ('I', 'Instructor'), ('T', 'TA'), ('A', 'Administrator')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Group')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assessment')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assessment_Question')),
                ('gradee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradee', to='peer_assessment.User')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grader', to='peer_assessment.User')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Class')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User')),
            ],
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Question'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Class'),
        ),
    ]
