# Generated by Django 3.0.4 on 2020-04-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0002_auto_20200420_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='professor_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='23737158', max_length=100),
        ),
    ]
