# Generated by Django 3.0.4 on 2020-04-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0003_auto_20200420_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='instructor_list_id',
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.CharField(default="<attribute 'year' of 'datetime.date' objects>", max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='85663309', max_length=100),
        ),
    ]
