# Generated by Django 3.0.4 on 2020-04-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0006_auto_20200420_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='39974079', max_length=100),
        ),
    ]
