# Generated by Django 3.0.4 on 2020-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0007_auto_20200420_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='completion',
        ),
        migrations.AddField(
            model_name='assessment',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Open Response', 'Open Response')], default='Multiple Choice', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='49116827', max_length=100),
        ),
    ]
