# Generated by Django 3.0.4 on 2020-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0008_auto_20200421_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='88436306', max_length=100),
        ),
    ]
