# Generated by Django 3.0.4 on 2020-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0010_auto_20200501_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='50567957', max_length=100),
        ),
    ]
