# Generated by Django 3.0.4 on 2020-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0011_auto_20200501_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='69769569', max_length=100),
        ),
    ]
